// Code generated by tool; DO NOT EDIT.
package syntax

type StmtVisitor interface {
	VisitBlockStmt(*Block) error
	VisitExpressionStmt(*Expression) error
	VisitPrintStmt(*Print) error
	VisitVarStmt(*Var) error
	VisitIfStmt(*If) error
}

type Stmt interface {
	 Accept(StmtVisitor) error
}

type Block struct {
	Statements []Stmt
}
func NewBlock(statements []Stmt) *Block {
	return &Block{
		Statements: statements,
	}
}
func (n *Block) Accept(v StmtVisitor) error {
	return v.VisitBlockStmt(n)
}

type Expression struct {
	Expression Expr
}
func NewExpression(expression Expr) *Expression {
	return &Expression{
		Expression: expression,
	}
}
func (n *Expression) Accept(v StmtVisitor) error {
	return v.VisitExpressionStmt(n)
}

type Print struct {
	Expression Expr
}
func NewPrint(expression Expr) *Print {
	return &Print{
		Expression: expression,
	}
}
func (n *Print) Accept(v StmtVisitor) error {
	return v.VisitPrintStmt(n)
}

type Var struct {
	Name Token
	Initializer Expr
}
func NewVar(name Token, initializer Expr) *Var {
	return &Var{
		Name: name,
		Initializer: initializer,
	}
}
func (n *Var) Accept(v StmtVisitor) error {
	return v.VisitVarStmt(n)
}

type If struct {
	Condition Expr
	Thenbranch Stmt
	Elsebranch Stmt
}
func NewIf(condition Expr, thenbranch Stmt, elsebranch Stmt) *If {
	return &If{
		Condition: condition,
		Thenbranch: thenbranch,
		Elsebranch: elsebranch,
	}
}
func (n *If) Accept(v StmtVisitor) error {
	return v.VisitIfStmt(n)
}

